import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#1A1A1A',
    flex: 1,
  },
  header: {
    height: 173,
    backgroundColor: '#0D0D0D',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  formContainer: {
    paddingHorizontal: 24,
    flexDirection: 'row',
    position: 'absolute',
    top: 146,
    gap: 4,
  },
  input: {
    height: 54,
    backgroundColor: '#262626',
    color: '#F2F2F2',
    borderStyle: 'solid',
    borderColor: '#0D0D0D',
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 16,
    borderRadius: 6,
  },
  button: {
    height: 52,
    width: 52,
    backgroundColor: '#1E6F9F',
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  todos: {
    paddingHorizontal: 24,
    marginTop: 59,
  },
  todosHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomColor: '#333333',
    borderBottomStyle: 'solid',
    borderBottomWidth: 1,
  },
  todosInfo: {
    flexDirection: 'row',
    gap: 8,
  },
  todosLabel: {
    color: '#4EA8DE',
    fontWeight: 'bold',
    fontSize: 14,
  },
  todosBox: {
    backgroundColor: '#333333',
    paddingHorizontal: 8,
    paddingVertical: 2,
    height: 19,
    borderRadius: 9.5, 
  },
  todosValue: {
    color: '#D9D9D9',
    fontWeight: 'bold',
    fontSize: 12,
  },
  todosEmpty: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  todosTitle: {
    color: '#808080',
    fontWeight: 'bold',
    fontSize: 14,
    marginTop: 16,
    marginBottom: 4,
  },
  todosSubtitle: {
    color: '#808080',
    fontSize: 14,
  },
  card: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#262626',
    borderColor: '#333333',
    borderStyle: 'solid',
    borderWidth: 1,
    gap: 8,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  cardButtonCheck: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unchecked: {
    height: 17.45,
    width: 17.45,
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#4EA8DE',
    borderRadius: 17.45,
  }, 
  checked: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 17.45,
    width: 17.45,
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#4EA8DE',
    borderRadius: 17.45,
    backgroundColor: '#4EA8DE',
  },
  cardText: {
    flex: 1,
    fontSize: 14,
    color: '#F2F2F2',
    lineHeight: 22,
  },
  cardButtonTrash: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  }
});
